version: '3.9'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: moderator
      POSTGRES_PASSWORD: moderator
      POSTGRES_DB: moderator_db
    ports:
      - "5432:5432"
